# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14E3siUZrogwiGZ7-Ohx6-lNpsJOU89mP
"""
# in order to measure time complexity as input size (n) 

import matplotlib.pyplot as plt
import numpy as np

x_vals = np.array([100, 1000, 10000, 100000, 1000000])
y_vals_time = np.array([305262, 605340, 4641540, 39939167, 275839622])
y_vals_nlogn = np.array([200, 3000, 40000, 500000, 6000000])

plt.figure(figsize=(8,8))
plt.plot(x_vals, y_vals_time, label='time complexity', marker='o', color='blue')
plt.plot(x_vals, y_vals_nlogn, label='nlogn comparison', marker='s', color='red')
plt.xlabel('input size (n)')
plt.ylabel('y values')
plt.title('comparison of time complexity and nlogn')
plt.xscale('log')
plt.yscale('log')
plt.legend()
plt.show()

